import os
import re
import ast
import unittest

class TestQualityGate(unittest.TestCase):
    def setUp(self):
        # Anchor to plugin root
        self.plugin_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))

    def get_all_files(self, extensions):
        target_files = []
        # Files that are generated by install.py should not be scanned by the quality gate
        generated_files = {"hooks.json", "sidecar.json", "SKILL.md"}
        
        for root, dirs, files in os.walk(self.plugin_root):
            # Skip virtualenvs, __pycache__, git, and scratch
            if ".git" in root or "__pycache__" in root or "node_modules" in root or "scratch" in root or ".agents" in root:
                continue
            for file in files:
                if file in generated_files or file == "ORIGINAL_REQUEST.md":
                    continue
                # For agents, ignore .json if it's not a template.json
                if "agents" in root and file.endswith(".json") and not file.endswith(".template.json"):
                    continue
                if any(file.endswith(ext) for ext in extensions):
                    target_files.append(os.path.join(root, file))
        return target_files

    def test_no_hardcoded_tmp_paths(self):
        bad_tmp_pattern = re.compile(r'/' + r'tmp/' + r'remora_')
        
        for file_path in self.get_all_files([".py", ".md", ".json"]):
            if file_path == os.path.abspath(__file__):
                continue
            with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
                content = f.read()
                matches = bad_tmp_pattern.findall(content)
                self.assertFalse(
                    matches, 
                    f"Quality Gate Failure: Hardcoded /tmp/ path found in {file_path}. Use SQLite or PLUGIN_ROOT/data/.runtime instead."
                )

    def test_no_hardcoded_absolute_gemini_paths(self):
        bad_home_pattern = re.compile(r'~' + r'/\.gemini/(?!antigravity)')
        bad_abs_pattern = re.compile(r'/home/[^/]+/\.gemini/(?!antigravity)')
        
        for file_path in self.get_all_files([".py", ".md", ".json"]):
            if file_path == os.path.abspath(__file__):
                continue
            # install.py legitimately needs to reference ~/.gemini for symlinking and db migration
            if os.path.basename(file_path) == "install.py":
                continue
            with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
                content = f.read()
                matches = bad_home_pattern.findall(content) or bad_abs_pattern.findall(content)
                self.assertFalse(
                    matches, 
                    f"Quality Gate Failure: Hardcoded ~/.gemini/ absolute path found in {file_path}. Use {{PLUGIN_ROOT}} templating."
                )

    def test_no_dangerous_file_reads(self):
        # Prevent f.readlines() and unbounded f.read()
        bad_readlines = re.compile(r'\.readlines\(' + r'\)')
        
        for file_path in self.get_all_files([".py"]):
            if file_path == os.path.abspath(__file__):
                continue
            with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
                content = f.read()
                matches = bad_readlines.findall(content)
                self.assertFalse(
                    matches, 
                    f"Quality Gate Failure: Unsafe .readlines() used in {file_path}. Violates LARGE FILE SAFETY rule."
                )

    def test_no_arbitrary_python_subprocess(self):
        # Prevent subprocess.run(["python3", ...])
        bad_python3 = re.compile(r'subprocess\.(?:run|Popen|call)\(\s*\[?\s*[\'"]python3[\'"]')
        
        for file_path in self.get_all_files([".py"]):
            if file_path == os.path.abspath(__file__):
                continue
            with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
                content = f.read()
                matches = bad_python3.findall(content)
                self.assertFalse(
                    matches, 
                    f"Quality Gate Failure: Hardcoded 'python3' in subprocess call in {file_path}. Use sys.executable instead."
                )

if __name__ == "__main__":
    unittest.main()
